language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
  - "2.1.2"
  - "jruby"
  - "rbx"
gemfile:
  - "Gemfile"
  - "gemfiles/Gemfile.multi_json.x"
  - "gemfiles/Gemfile.yajl-ruby.x"
  - "gemfiles/Gemfile.uuidtools.x"
matrix:
  exclude:
    - rvm: "jruby"
      gemfile: "gemfiles/Gemfile.yajl-ruby.x"